/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    articles: Article;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    pages: {
      subPages: 'pages';
      primaryArticles: 'articles';
      secondaryArticles: 'articles';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  legacyUserId?: number | null;
  username?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  description?: string | null;
  myWebUrl?: string | null;
  avatar?: (number | null) | Media;
  roles: ('admin' | 'editor' | 'user')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  r2BackupStatus?: ('pending' | 'success' | 'error') | null;
  cloudinaryPublicId?: string | null;
  cloudinaryUrl?: string | null;
  cloudinaryResourceType?: string | null;
  cloudinaryFormat?: string | null;
  cloudinaryVersion?: number | null;
  /**
   * Direct URL to the original file without transformations
   */
  originalUrl?: string | null;
  /**
   * URL with applied transformations
   */
  transformedUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  /**
   * File size in bytes
   */
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  category:
    | 'Místo k navštívení'
    | 'Turistický cíl'
    | 'Místa'
    | 'Praktické informace'
    | 'Vstupní podmínky'
    | 'Cesta'
    | 'Počasí'
    | 'Doprava'
    | 'Měna a ceny'
    | 'Zdraví a bezpečí'
    | 'Jazyk a kultura'
    | 'Jídlo a pití'
    | 'Ubytování'
    | 'Články';
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: {
    image?: (number | null) | Media;
    featureImageStyleCss?: string | null;
    cloudinarySetting?: string | null;
    isCreativeCommons?: boolean | null;
    author?: string | null;
    description?: string | null;
    source?: string | null;
    sourceLink?: string | null;
    creativeCommonsLicense?: string | null;
    /**
     * Zde vložte kód SVG (volitelné)
     */
    svgCode?: string | null;
  };
  detail?: {
    googleMapsAddress?: string | null;
    latitude?: string | null;
    longitude?: string | null;
    googleMapsZoom?: number | null;
    locative?: string | null;
    genitive?: string | null;
    timezone?: string | null;
    currencyCode?: string | null;
    showWeather?: boolean | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  affiliate?: {
    toursUrl?: string | null;
    accommodationUrl?: string | null;
    carRentalUrl?: string | null;
    kiwiIataCode?: string | null;
  };
  slug?: string | null;
  legacyPageId?: number | null;
  createdBy?: (number | null) | User;
  parent?: (number | null) | Page;
  fullSlug?: string | null;
  includeInChildUrlPaths?: boolean | null;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  subPages?: {
    docs?: (number | Page)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  primaryArticles?: {
    docs?: (number | Article)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  secondaryArticles?: {
    docs?: (number | Article)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  category: 'Článek' | 'Průvodce' | 'RadyNaCestu';
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: {
    image?: (number | null) | Media;
    featureImageStyleCss?: string | null;
    cloudinarySetting?: string | null;
    isCreativeCommons?: boolean | null;
    author?: string | null;
    description?: string | null;
    source?: string | null;
    sourceLink?: string | null;
    creativeCommonsLicense?: string | null;
    /**
     * Zde vložte kód SVG (volitelné)
     */
    svgCode?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  slug?: string | null;
  createdBy?: (number | null) | User;
  /**
   * Určuje výslednou domovskou URL adresu článku a kanonický odkaz pro Google.
   */
  mainPage?: (number | null) | Page;
  /**
   * Vyberte další destinace, ve kterých se má tento článek zobrazit v doporučeném výpisu.
   */
  pages?: (number | Page)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  legacyUserId?: T;
  username?: T;
  firstName?: T;
  lastName?: T;
  description?: T;
  myWebUrl?: T;
  avatar?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  r2BackupStatus?: T;
  cloudinaryPublicId?: T;
  cloudinaryUrl?: T;
  cloudinaryResourceType?: T;
  cloudinaryFormat?: T;
  cloudinaryVersion?: T;
  originalUrl?: T;
  transformedUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  text?: T;
  featuredImage?:
    | T
    | {
        image?: T;
        featureImageStyleCss?: T;
        cloudinarySetting?: T;
        isCreativeCommons?: T;
        author?: T;
        description?: T;
        source?: T;
        sourceLink?: T;
        creativeCommonsLicense?: T;
        svgCode?: T;
      };
  detail?:
    | T
    | {
        googleMapsAddress?: T;
        latitude?: T;
        longitude?: T;
        googleMapsZoom?: T;
        locative?: T;
        genitive?: T;
        timezone?: T;
        currencyCode?: T;
        showWeather?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  affiliate?:
    | T
    | {
        toursUrl?: T;
        accommodationUrl?: T;
        carRentalUrl?: T;
        kiwiIataCode?: T;
      };
  slug?: T;
  legacyPageId?: T;
  createdBy?: T;
  parent?: T;
  fullSlug?: T;
  includeInChildUrlPaths?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  subPages?: T;
  primaryArticles?: T;
  secondaryArticles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  text?: T;
  featuredImage?:
    | T
    | {
        image?: T;
        featureImageStyleCss?: T;
        cloudinarySetting?: T;
        isCreativeCommons?: T;
        author?: T;
        description?: T;
        source?: T;
        sourceLink?: T;
        creativeCommonsLicense?: T;
        svgCode?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  slug?: T;
  createdBy?: T;
  mainPage?: T;
  pages?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  title: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: {
    link?: {
      title?: string | null;
      href?: string | null;
      isExternal?: boolean | null;
      isButtonLink?: boolean | null;
    };
    image?: (number | null) | Media;
    svgCode?: string | null;
  };
  navItems?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: {
    link?: {
      title?: string | null;
      href?: string | null;
      isExternal?: boolean | null;
      isButtonLink?: boolean | null;
      id?: string | null;
    };
    image?: (number | null) | Media;
    svgCode?: string | null;
  };
  navItems?:
    | {
        title?: string | null;
        href?: string | null;
        isExternal?: boolean | null;
        isButtonLink?: boolean | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        link?:
          | T
          | {
              title?: T;
              href?: T;
              isExternal?: T;
              isButtonLink?: T;
            };
        image?: T;
        svgCode?: T;
      };
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        link?:
          | T
          | {
              title?: T;
              href?: T;
              isExternal?: T;
              isButtonLink?: T;
              id?: T;
            };
        image?: T;
        svgCode?: T;
      };
  navItems?:
    | T
    | {
        title?: T;
        href?: T;
        isExternal?: T;
        isButtonLink?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapBlock".
 */
export interface MapBlock {
  iframeUrl: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mapBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeasonalityBlock".
 */
export interface SeasonalityBlock {
  prefixText?: string | null;
  idealMonthsText?: string | null;
  months?:
    | {
        monthNumber: number;
        status: 'off' | 'mid' | 'peak';
        id?: string | null;
      }[]
    | null;
  legend?:
    | {
        status: 'off' | 'mid' | 'peak';
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'seasonalityBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NiceToKnowBlock".
 */
export interface NiceToKnowBlock {
  items?:
    | {
        type: 'language' | 'electricity' | 'currency' | 'weather' | 'time';
        headerText?: string | null;
        headerSubtext?: string | null;
        title: string;
        value: string;
        /**
         * Pokud zůstane prázdné, použije se nastavení z detailu stránky.
         */
        timezone?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'niceToKnowBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DailyCostsBlock".
 */
export interface DailyCostsBlock {
  heading?: string | null;
  columns?:
    | {
        tier: 'budget' | 'midrange' | 'top';
        rangeLabel: string;
        price: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dailyCostsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}